services:
  - type: web
    name: neurosense-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -w 1 -b 0.0.0.0:$PORT --timeout 300"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: neurosense-frontend
    env: node
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist -l $PORT"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: neurosense-backend
          envVarKey: RENDER_EXTERNAL_URL
